name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login DockerHub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" |  docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build image 
      run: docker build . --file Dockerfile --tag egesa/poultry:latest

    - name: Push to Dockerhub
      run: docker push egesa/poultry:latest
